### ISSUE TITLE
Python 3.7 / asyncio / Serial has no attribute 'serial_for_url'

### ISSUE THREAD

**Issue by CncFanatic** [wolfmanjm/kivy-smoothie-host#11]
Hello,

First, thank you for your awesome work on Smoothie and all other goodies you write around it.
Before use SMoopi on Rpi, i will try it on a Windows desktop.

With all your documentation and Kivy website, I was ready to launch Soompi.

Target : Python 3.7.2

I had an issue with asyncio.async with Python 3.7.2 in Comm.py
I'm not Python developer, i try to change ->
line 327: asyncio.async(self._parse_sdcard_list(done_cb)) to asyncio.run(self._parse_sdcard_list(done_cb))
line 574: self.file_streamer = asyncio.async(self.stream_file(fn)) to self.file_streamer = asyncio.run(self.stream_file(fn))

After installing other missing package in WinPython3.7.2 (pyserial-asyncio and aiofiles), Smoopi starts ! Great !

My SmoothieBoard is located on COM18 (fully working board..).
On Smoopi, I'm able to select the port (serial://COM18).

Unfortunately on "Connect" i have this message : Got serial error opening port : module 'serial' has no attribute 'serial for url'.

Thank you.

Regards,
Chris.

**Comment by wolfmanjm** [comment]
Python 3.7 is not supported you have to use 3.4 upto 3.6.

It clearly  states in the README...

Currently does not run on python versions > 3.6 due to async changes.

**Comment by CncFanatic** [comment]
Hello
All my apology.
I start again in 3.6
Regards,
Chris

**Comment by wolfmanjm** [comment]
fwiw smoopi will  now work with python 3.7
